# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "new-qr-code"
client_id = "9cf68fff48a5d3bbbbc2ba95ff2f043d"
application_url = "https://nylon-enforcement-holiday-realm.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nylon-enforcement-holiday-realm.trycloudflare.com/auth/callback",
  "https://nylon-enforcement-holiday-realm.trycloudflare.com/auth/shopify/callback",
  "https://nylon-enforcement-holiday-realm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avocation-test.myshopify.com"
